# Generated by Django 5.1.5 on 2025-02-01 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("view_count", models.IntegerField(default=0)),
                ("access_token", models.CharField(max_length=100, unique=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("one_time_view", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "snippets",
                "indexes": [
                    models.Index(
                        fields=["access_token"], name="snippets_access__f7bddb_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="snippets_expires_0453e1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnippetView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_hash", models.CharField(max_length=64)),
                ("user_agent", models.CharField(max_length=255)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="snippets.snippet",
                    ),
                ),
            ],
            options={
                "db_table": "snippet_views",
                "indexes": [
                    models.Index(
                        fields=["snippet", "viewed_at"],
                        name="snippet_vie_snippet_b06c36_idx",
                    )
                ],
            },
        ),
    ]
