# Generated by Django 5.1.5 on 2025-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_snippetmetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="VSCodeExtensionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_actions", models.PositiveIntegerField(default=0)),
                ("selection_shares", models.PositiveIntegerField(default=0)),
                ("file_shares", models.PositiveIntegerField(default=0)),
                ("unique_clients", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "vscode_extension_metrics",
            },
        ),
    ]
