# Generated by Django 5.1.5 on 2025-02-28 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_snippetmetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="parent_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="snippets.snippet",
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="password_salt",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="SnippetDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diff_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_diffs",
                        to="snippets.snippet",
                    ),
                ),
                (
                    "target_snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_diffs",
                        to="snippets.snippet",
                    ),
                ),
            ],
            options={
                "db_table": "snippet_diffs",
                "unique_together": {("source_snippet", "target_snippet")},
            },
        ),
    ]
