# Generated by Django 5.1.5 on 2025-05-01 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_vscodetelemetryevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnippetDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diff_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "snippet_diffs",
            },
        ),
        migrations.DeleteModel(
            name="VSCodeExtensionMetrics",
        ),
        migrations.DeleteModel(
            name="VSCodeTelemetryEvent",
        ),
        migrations.AddField(
            model_name="snippet",
            name="creator_ip_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="creator_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="parent_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="snippets.snippet",
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="password_salt",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="snippetview",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="snippetdiff",
            name="source_snippet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_diffs",
                to="snippets.snippet",
            ),
        ),
        migrations.AddField(
            model_name="snippetdiff",
            name="target_snippet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_diffs",
                to="snippets.snippet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="snippetdiff",
            unique_together={("source_snippet", "target_snippet")},
        ),
    ]
