# Generated by Django 5.1.5 on 2025-05-01 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0005_snippetdiff_delete_vscodeextensionmetrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VSCodeExtensionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_actions", models.PositiveIntegerField(default=0)),
                ("selection_shares", models.PositiveIntegerField(default=0)),
                ("file_shares", models.PositiveIntegerField(default=0)),
                ("unique_clients", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "vscode_extension_metrics",
            },
        ),
        migrations.CreateModel(
            name="VSCodeTelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_name", models.CharField(max_length=50)),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField()),
                (
                    "vs_code_version",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("code_length", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "vscode_telemetry_events",
                "indexes": [
                    models.Index(
                        fields=["event_name", "timestamp"],
                        name="vscode_tele_event_n_0c31ab_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="vscode_tele_timesta_59cd04_idx"
                    ),
                ],
            },
        ),
    ]
