# Generated by Django 5.1.5 on 2025-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0006_vscodeextensionmetrics_vscodetelemetryevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="creator_ip_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="password_salt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
