# Generated by Django 5.1.5 on 2025-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0007_alter_snippet_creator_ip_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="encryption_salt",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="password_salt",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
