# Generated by Django 5.1 on 2025-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0008_snippet_encryption_salt_alter_snippet_password_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="snippet",
            name="public_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="password_salt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["is_public", "expires_at", "created_at"],
                name="snippets_is_publ_04ed86_idx",
            ),
        ),
    ]
