# Generated by Django 5.1 on 2025-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0009_remove_snippet_encryption_salt_snippet_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="is_consumed",
            field=models.BooleanField(default=False),
        ),
    ]
