# Generated by Django 5.1.5 on 2025-12-09 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0011_fixed_migration"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE snippets DROP COLUMN IF EXISTS encryption_salt;",
            reverse_sql="ALTER TABLE snippets ADD COLUMN encryption_salt varchar(128);",
        ),
        migrations.AddField(
            model_name="snippet",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="max_views",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SecretScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("matched_fragment", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="snippets.snippet",
                    ),
                ),
            ],
            options={
                "db_table": "secret_scan_logs",
                "indexes": [
                    models.Index(
                        fields=["snippet", "created_at"],
                        name="secret_scan_snippet_fa35f3_idx",
                    ),
                    models.Index(
                        fields=["rule_type", "severity"],
                        name="secret_scan_rule_ty_cf12be_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnippetComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("delete_token", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="snippets.snippet",
                    ),
                ),
            ],
            options={
                "db_table": "snippet_comments",
                "indexes": [
                    models.Index(
                        fields=["snippet", "-created_at"],
                        name="snippet_com_snippet_9a6c11_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="snippet_com_ip_hash_7bab9d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnippetReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reaction_type", models.CharField(max_length=20)),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="snippets.snippet",
                    ),
                ),
            ],
            options={
                "db_table": "snippet_reactions",
                "indexes": [
                    models.Index(
                        fields=["snippet", "reaction_type"],
                        name="snippet_rea_snippet_71342c_idx",
                    )
                ],
                "unique_together": {("snippet", "reaction_type")},
            },
        ),
    ]
