# Generated by Django 5.1.5 on 2026-05-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0013_alter_snippet_expires_at_nullable"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="snippet",
                    name="encryption_salt",
                ),
            ],
            database_operations=[],
        ),
    ]
